image: docker:stable

variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_IMAGE_NAME: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG"
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: test-pass
    POSTGRES_DB: testdb
    HELM_NAME: "golemio"
    K8S_DEPLOYMENT_NAME: integration-engine
    K8S_DEPLOYMENT_IMAGE_TAG: $CI_PIPELINE_ID

include:
    - template: "Workflows/Branch-Pipelines.gitlab-ci.yml"
    - project: "operator-ict/devops/gitlab-ci-pipeline"
      file:
          - "/docker/simple-build.yml"
          - "/k8s-golemio/helm-golemio-deploy.yml"
          - "/docs/golemio-gitlab-docs-pages.yml"

cache:
    key:
        files:
            - yarn.lock
    paths:
        - node_modules

stages:
    - test
    - build
    - release
    - deploy

.run_tests:
    stage: test
    services:
        - postgres:13.6
        - mongo:4.0
        - redis:6.2-alpine
        - rabbitmq:3.9
    script:
        - export NODE_ENV=development
        - export LOG_LEVEL=warn
        - yarn
        # Audit production dependencies for HIGH (8) vulnerabilities
        # https://classic.yarnpkg.com/en/docs/cli/audit/#toc-yarn-audit
        # TODO temporarily set level to critical
        - bash -c 'yarn audit --groups dependencies --level critical; [[ $? -ge 16 ]] && exit 1 || exit 0'
        - yarn lint
        - yarn build
        - export MONGO_CONN=mongodb://mongo/testdb
        - export POSTGRES_CONN=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB
        - export REDIS_CONN=redis://redis/
        - export NODE_ENV=test
        - export OPEN_STREET_MAP_API_URL_SEARCH=$OPEN_STREET_MAP_API_URL_SEARCH
        - export OPEN_STREET_MAP_API_URL_REVERSE=$OPEN_STREET_MAP_API_URL_REVERSE
        - export RABBIT_CONN=amqp://guest:guest@rabbitmq
        - export RABBIT_EXCHANGE_NAME=citests
        - export S3_BUCKET_NAME=integration-engine
        - export S3_UPLOAD_PART_SIZE=10
        - export S3_UPLOAD_QUEUE_SIZE=2
        - yarn code-coverage
    tags:
        - docker
    rules:
        - when: always
    artifacts:
        when: always
        reports:
            junit: junit.xml
            coverage_report:
                coverage_format: cobertura
                path: coverage/cobertura-coverage.xml

run_tests:
    extends: .run_tests
    image: bitnami/node:16.13.0

up_down_migrations:
    stage: test
    image: bitnami/node:16.13.0
    services:
        - name: postgis/postgis:13-3.2
          alias: postgres
    script:
        - export POSTGRES_CONN=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB
        # Run migrations from schema definitions
        - export SCH_NPM_TAG="dev" && [[ "$CI_COMMIT_REF_NAME" == "master" ]] && export SCH_NPM_TAG="latest"
        - export SCH_VERSION=$(npm show @golemio/schema-definitions@$SCH_NPM_TAG version)
        - export SCH_DIR=$(mktemp -d)
        - echo "Installing schema-definitions version $SCH_VERSION"
        - npm i --prefix $SCH_DIR @golemio/schema-definitions@$SCH_VERSION
        - bash -c "cd $SCH_DIR/node_modules/@golemio/schema-definitions && npm run migrate-postgres-db >/dev/null && cd -"
        # Run migrations from modules
        - export POSTGRES_MIGRATIONS_DIR=node_modules/@golemio/**/db/migrations/**/postgresql
        - yarn
        # TODO remove; Temporary solution, pid module really should not be here (external tests yada yada)
        - rm -rf node_modules/@golemio/pid/db/migrations
        - yarn golemio migrate-db up --postgres
        - yarn golemio migrate-db reset --postgres
    tags:
        - docker
    rules:
        - when: always
