variables:
  CONTAINER_IMAGE: gitlab.oict.cz:4567/$CI_PROJECT_PATH

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.oict.cz:4567

stages:
  - build
  - test
  - deploy
  - clean

build_image:
  stage: build
  script:
    - docker build -t $CONTAINER_IMAGE:latest -t $CONTAINER_IMAGE:$CI_PIPELINE_ID .

run_tests:
  stage: test
  script:
    - docker run $CONTAINER_IMAGE npm run code-coverage

registry_deployment:
  stage: deploy
  script:
    - docker push $CONTAINER_IMAGE:latest && docker push $CONTAINER_IMAGE:$CI_PIPELINE_ID
  only:
    refs:
      - master
      
remove_images:
  stage: clean
  script:
    - docker rmi $CONTAINER_IMAGE
 