variables:
  CONTAINER_IMAGE: gitlab.oict.cz:4567/$CI_PROJECT_PATH

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.oict.cz:4567

build_image:
   script:
     - docker build -t $CONTAINER_IMAGE .
     - docker push $CONTAINER_IMAGE
