module.exports = {
    CeskyCarsharingSharedCars: "https://api.ceskycarsharing.cz/iis_cs_api/IIS_API.svc/getAllCarsIct",
    CeskyCarsharingSharedCarsEndpointCredentials: {
        guid: "",
        password: "",
    },
    CityDistricts: "http://opendata.iprpraha.cz/CUR/DTMP/TMMESTSKECASTI_P/WGS_84/TMMESTSKECASTI_P.json",
    HoppyGoSharedCars: "https://www.hoppygo.com/api/v1/exports/cars_search",
    IGSensors: "https://prague-city.ice-gateway.com/iceapi/v1/iot/data/all/?per_page=200",
    IGStreetLamp: "https://prague-city.ice-gateway.com/iceapi/v1/streetlamp/",
    IGStreetLamps: "https://prague-city.ice-gateway.com/iceapi/v1/streetlamps/",
    IGToken: "myStringToken",
    ParkingZones: "http://opendata.iprpraha.cz/CUR/DOP/DOP_ZPS_USEKY_p/WGS_84/DOP_ZPS_USEKY_p.json",
    ParkingZonesTariffs: "http://opendata.iprpraha.cz/CUR/DOP/DOP_ZPS_ZonyStani_p/TARIF.csv",
    RopidFTP: {
        host: "",
        password: "",
        secure: null,
        user: "",
    },
    RopidGTFSCisStopsFilename: "Stops.Min.json",
    RopidGTFSCisStopsPath: "PUBLIC/ZASTAVKY/JSON/",
    RopidGTFSFilename: "PID_GTFS.zip",
    RopidGTFSPath: "GTFS/",
    TSKParkings: "http://www.tsk-praha.cz/tskexport3/json/parkings",
    TSKTrafficCameras: "http://www.tsk-praha.cz/tskexport3/json/cameras",
};
