module.exports = {
    AirQualityStations: "http://portal.chmi.cz/files/portal/docs/uoco/web_generator/AIMdata_hourly.xml",
    CeskyCarsharingSharedCars: "https://api.ceskycarsharing.cz/iis_cs_api/IIS_API.svc/getAllCarsIct",
    CeskyCarsharingSharedCarsEndpointCredentials: {
        guid: "",
        password: "",
    },
    CityDistricts: "http://opendata.iprpraha.cz/CUR/DTMP/TMMESTSKECASTI_P/WGS_84/TMMESTSKECASTI_P.json",
    Gardens: "https://www.mojepraha.eu/api/gardens",
    HoppyGoSharedCars: "https://www.hoppygo.com/api/v1/exports/cars_search",
    IGSensors: "https://prague-city.ice-gateway.com/iceapi/v1/iot/data/all/?per_page=200",
    IGStreetLamp: "https://prague-city.ice-gateway.com/iceapi/v1/streetlamp/",
    IGStreetLamps: "https://prague-city.ice-gateway.com/iceapi/v1/streetlamps/",
    IGToken: "myStringToken",
    MedicalInstitutions: "https://opendata.sukl.cz/soubory/SODERECEPT/LEKARNYAKTUALNI.zip",
    MunicipalAuthorities: "https://www.mojepraha.eu/api/municipal-authorities",
    MunicipalPoliceStations: "http://opendata.iprpraha.cz/CUR/FSB/BEZ_ObjektMPP_b/WGS_84/BEZ_ObjektMPP_b.json",
    ParkingZones: "http://opendata.iprpraha.cz/CUR/DOP/DOP_ZPS_USEKY_p/WGS_84/DOP_ZPS_USEKY_p.json",
    ParkingZonesTariffs: "http://opendata.iprpraha.cz/CUR/DOP/DOP_ZPS_ZonyStani_p/TARIF.csv",
    Playgrounds: "http://www.hristepraha.cz/api/get-all-items?type=hriste",
    PublicToilets: "http://opendata.iprpraha.cz/CUR/FSV/FSV_VerejnaWC_b/WGS_84/FSV_VerejnaWC_b.json",
    RopidFTP: {
        host: "",
        password: "",
        secure: null,
        user: "",
    },
    RopidGTFSCisStopsFilename: "Stops.Min.json",
    RopidGTFSCisStopsPath: "PUBLIC/ZASTAVKY/JSON/",
    RopidGTFSFilename: "PID_GTFS.zip",
    RopidGTFSPath: "GTFS/",
    SkodaPalaceQueues: "http://jungmannova.webcall.praha.eu/mon/wc-mon.php",
    TSKMeteosensors: "http://www.tsk-praha.cz/tskexport3/json/meteosensors",
    TSKParkings: "http://www.tsk-praha.cz/tskexport3/json/parkings",
    TSKTrafficCameras: "http://www.tsk-praha.cz/tskexport3/json/cameras",
    WasteCollectionYards: "http://opendata.iprpraha.cz/CUR/ZPK/ZPK_O_SberOdpadu_b/WGS_84/ZPK_O_SberOdpadu_b.json",
};
